// automatically generated by the FlatBuffers compiler, do not modify

package KartKraft;

public final class Surface {
  private Surface() { }
  public static final byte None = 0;
  public static final byte Asphalt = 1;
  public static final byte Grass = 2;
  public static final byte Gravel = 3;
  public static final byte Kerb = 4;
  public static final byte Sand = 5;
  public static final byte Tyre = 6;

  public static final String[] names = { "None", "Asphalt", "Grass", "Gravel", "Kerb", "Sand", "Tyre", };

  public static String name(int e) { return names[e]; }
}

