// automatically generated by the FlatBuffers compiler, do not modify

package KartKraft;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class TrackConfig extends Table {
  public static TrackConfig getRootAsTrackConfig(ByteBuffer _bb) { return getRootAsTrackConfig(_bb, new TrackConfig()); }
  public static TrackConfig getRootAsTrackConfig(ByteBuffer _bb, TrackConfig obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public TrackConfig __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int numSectors() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }

  public static int createTrackConfig(FlatBufferBuilder builder,
      int nameOffset,
      int numSectors) {
    builder.startObject(2);
    TrackConfig.addName(builder, nameOffset);
    TrackConfig.addNumSectors(builder, numSectors);
    return TrackConfig.endTrackConfig(builder);
  }

  public static void startTrackConfig(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addNumSectors(FlatBufferBuilder builder, int numSectors) { builder.addByte(1, (byte)numSectors, (byte)0); }
  public static int endTrackConfig(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

