// automatically generated by the FlatBuffers compiler, do not modify

package KartKraft;

public final class VehicleState {
  private VehicleState() { }
  public static final byte Unknown = 0;
  public static final byte Pits = 1;
  public static final byte Outlap = 2;
  public static final byte Racing = 3;
  public static final byte Retired = 4;

  public static final String[] names = { "Unknown", "Pits", "Outlap", "Racing", "Retired", };

  public static String name(int e) { return names[e]; }
}

