// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace KartKraft
{

using global::System;
using global::FlatBuffers;

/// Motion data of local player for driving hardware motion simulators
public struct Motion : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Motion GetRootAsMotion(ByteBuffer _bb) { return GetRootAsMotion(_bb, new Motion()); }
  public static Motion GetRootAsMotion(ByteBuffer _bb, Motion obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Motion __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float Pitch { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Roll { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Yaw { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float AccelerationX { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float AccelerationY { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float AccelerationZ { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float TractionLoss { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float VelocityX { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float VelocityY { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float VelocityZ { get { int o = __p.__offset(22); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float AngularVelocityX { get { int o = __p.__offset(24); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float AngularVelocityY { get { int o = __p.__offset(26); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float AngularVelocityZ { get { int o = __p.__offset(28); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<Motion> CreateMotion(FlatBufferBuilder builder,
      float pitch = 0.0f,
      float roll = 0.0f,
      float yaw = 0.0f,
      float accelerationX = 0.0f,
      float accelerationY = 0.0f,
      float accelerationZ = 0.0f,
      float tractionLoss = 0.0f,
      float velocityX = 0.0f,
      float velocityY = 0.0f,
      float velocityZ = 0.0f,
      float angularVelocityX = 0.0f,
      float angularVelocityY = 0.0f,
      float angularVelocityZ = 0.0f) {
    builder.StartObject(13);
    Motion.AddAngularVelocityZ(builder, angularVelocityZ);
    Motion.AddAngularVelocityY(builder, angularVelocityY);
    Motion.AddAngularVelocityX(builder, angularVelocityX);
    Motion.AddVelocityZ(builder, velocityZ);
    Motion.AddVelocityY(builder, velocityY);
    Motion.AddVelocityX(builder, velocityX);
    Motion.AddTractionLoss(builder, tractionLoss);
    Motion.AddAccelerationZ(builder, accelerationZ);
    Motion.AddAccelerationY(builder, accelerationY);
    Motion.AddAccelerationX(builder, accelerationX);
    Motion.AddYaw(builder, yaw);
    Motion.AddRoll(builder, roll);
    Motion.AddPitch(builder, pitch);
    return Motion.EndMotion(builder);
  }

  public static void StartMotion(FlatBufferBuilder builder) { builder.StartObject(13); }
  public static void AddPitch(FlatBufferBuilder builder, float pitch) { builder.AddFloat(0, pitch, 0.0f); }
  public static void AddRoll(FlatBufferBuilder builder, float roll) { builder.AddFloat(1, roll, 0.0f); }
  public static void AddYaw(FlatBufferBuilder builder, float yaw) { builder.AddFloat(2, yaw, 0.0f); }
  public static void AddAccelerationX(FlatBufferBuilder builder, float accelerationX) { builder.AddFloat(3, accelerationX, 0.0f); }
  public static void AddAccelerationY(FlatBufferBuilder builder, float accelerationY) { builder.AddFloat(4, accelerationY, 0.0f); }
  public static void AddAccelerationZ(FlatBufferBuilder builder, float accelerationZ) { builder.AddFloat(5, accelerationZ, 0.0f); }
  public static void AddTractionLoss(FlatBufferBuilder builder, float tractionLoss) { builder.AddFloat(6, tractionLoss, 0.0f); }
  public static void AddVelocityX(FlatBufferBuilder builder, float velocityX) { builder.AddFloat(7, velocityX, 0.0f); }
  public static void AddVelocityY(FlatBufferBuilder builder, float velocityY) { builder.AddFloat(8, velocityY, 0.0f); }
  public static void AddVelocityZ(FlatBufferBuilder builder, float velocityZ) { builder.AddFloat(9, velocityZ, 0.0f); }
  public static void AddAngularVelocityX(FlatBufferBuilder builder, float angularVelocityX) { builder.AddFloat(10, angularVelocityX, 0.0f); }
  public static void AddAngularVelocityY(FlatBufferBuilder builder, float angularVelocityY) { builder.AddFloat(11, angularVelocityY, 0.0f); }
  public static void AddAngularVelocityZ(FlatBufferBuilder builder, float angularVelocityZ) { builder.AddFloat(12, angularVelocityZ, 0.0f); }
  public static Offset<Motion> EndMotion(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Motion>(o);
  }
};


}
