# automatically generated by the FlatBuffers compiler, do not modify

# namespace: KartKraft

class Surface(object):
    None_ = 0
    Asphalt = 1
    Grass = 2
    Gravel = 3
    Kerb = 4
    Sand = 5
    Tyre = 6

