# automatically generated by the FlatBuffers compiler, do not modify

# namespace: KartKraft

import flatbuffers

class TrackConfig(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTrackConfig(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TrackConfig()
        x.Init(buf, n + offset)
        return x

    # TrackConfig
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TrackConfig
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TrackConfig
    def NumSectors(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def TrackConfigStart(builder): builder.StartObject(2)
def TrackConfigAddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def TrackConfigAddNumSectors(builder, numSectors): builder.PrependUint8Slot(1, numSectors, 0)
def TrackConfigEnd(builder): return builder.EndObject()
