# automatically generated by the FlatBuffers compiler, do not modify

# namespace: KartKraft

# /// State of vehicle
class VehicleState(object):
    Idle = 0
    Pits = 1
    PitGrid = 2
    Outlap = 3
    RollingStart = 4
    FlyingStart = 5
    StartGrid = 6
    Racing = 7
    Retired = 8
    Finished = 9

