# automatically generated by the FlatBuffers compiler, do not modify

# namespace: KartKraft

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Wheel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsWheel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Wheel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def WheelBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x4B\x46\x42", size_prefixed=size_prefixed)

    # Wheel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Wheel
    def Surface(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Wheel
    def SlipAngle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def WheelStart(builder): builder.StartObject(2)
def WheelAddSurface(builder, surface): builder.PrependUint8Slot(0, surface, 0)
def WheelAddSlipAngle(builder, slipAngle): builder.PrependFloat32Slot(1, slipAngle, 0.0)
def WheelEnd(builder): return builder.EndObject()
