# automatically generated by the FlatBuffers compiler, do not modify

# namespace: KartKraft

import flatbuffers

# /// Session data
class Session(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSession(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Session()
        x.Init(buf, n + offset)
        return x

    # Session
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Session
    def TotalTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Session
    def TimeLeft(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Session
    def TotalLaps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Session
    def Vehicles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Vehicle import Vehicle
            obj = Vehicle()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Session
    def VehiclesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def SessionStart(builder): builder.StartObject(4)
def SessionAddTotalTime(builder, totalTime): builder.PrependInt32Slot(0, totalTime, 0)
def SessionAddTimeLeft(builder, timeLeft): builder.PrependInt32Slot(1, timeLeft, 0)
def SessionAddTotalLaps(builder, totalLaps): builder.PrependInt32Slot(2, totalLaps, 0)
def SessionAddVehicles(builder, vehicles): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(vehicles), 0)
def SessionStartVehiclesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def SessionEnd(builder): return builder.EndObject()
